name: Build and Create EXE

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
